### ISSUE TITLE
Script not replacing drops as expected.

### ISSUE THREAD

**Issue by Tedyhere** [codetaylor/dropt#11]
My script, 

https://pastebin.com/B8bPWLc0

Should be replacing the block biomesoplenty:log_4:5

with a weighted list of dead planks and sticks 75% of the time or charcoal and sticks 25% of the time.

Not only does it not replace the drop, it adds to the drops so it drops the dead log, dead plank and stick, or the dead log, charcoal and stick.
It also does this with any biomesoplenty block as far as I can tell.

Dropt version 1.12.2-1.6.5
Anthenaeum version 1.12.2-1.9.5
Forge 2617

**Comment by codetaylor** [comment]
> Not only does it not replace the drop, it adds to the drops so it drops the dead log, dead plank and stick, or the dead log, charcoal and stick.

This is the proper behavior.

From the documentation:
> `REPLACE_ITEMS_IF_SELECTED`: All items defined in the IRuleMatch will be removed if and only if drops are selected from this rule.

This means that if you have any items defined in the IRuleMatch section, those items and only those items will be removed and replaced with the selected drops. You have defined blocks to match, but don't have any items to match defined in the section. See [IRuleMatch](https://github.com/codetaylor/dropt/blob/master/SYNTAX.md#irulematch) - it has a section for blocks and drops. The drops section is used to define item matching criteria.

Use `REPLACE_ALL_IF_SELECTED` instead. It will replace all block drops.

Also, please update to the latest version, 1.12.2-1.6.6, as it fixes a meta matching issue where it will always match a meta of 0 when it shouldn't.

Please let me know if this helps you, thanks.

**Comment by Tedyhere** [comment]
Wierd... sometimes I hate TwitchApp  It didn't show an update just a bit ago.. I will test again with Changes

**Comment by Tedyhere** [comment]
Confirmed it works as expected now.
