### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by Fortist** [codetaylor/dropt#15]
So, I want to have it where when mining with a certain item, certain things drop from a certain block.
Ergo, When mining COBBLESTONE with a WOODEN HAMMER drop the cobblestone and A DUST.

Your example got me started, I guess, but the wall of text that is syntax doesnt.
What does "IF SELECTED" mean?

Im sorry, but I just get dyslexic when it comes to walls of text, and Examples are the best use for me.

**Comment by Fortist** [comment]
Well, Im as far as having cobblestone drop dye 25% of the time with itself.

So, what Im trying to do is make the "drops" section change depending on what item you're mining it with, giving different items depending on which Mining tool you're using.

**Comment by codetaylor** [comment]
When I get some time, I'll add some more examples.

**Comment by TimGoll** [comment]
I second this. I have a hard time figuring stuff out. Maybe add some very basic examples

**Comment by codetaylor** [comment]
I'll be adding new examples here: https://dropt.readthedocs.io/en/latest/

**Comment by codetaylor** [comment]
I'm going to close this. Please create a new issue if you would like a specific example added to the example page linked above.

**Comment by TimGoll** [comment]
I really like your new documentation and I figured most things out by myself by now :)
