### ISSUE TITLE
Natural leaf decay not dropping items

### ISSUE THREAD

**Issue by Luke616** [codetaylor/dropt#17]
Trying to add custom drops to the leaves of a tree, but the drops are only occurring when broken by hand.

Here is a pastebin of the relevant config file https://pastebin.com/TwWaVfvf

Harvester type is left blank, which should default to ANY - although I have tried adding that line and specifying ANY but the result is the same.

Using: 
Minecraft 1.12.2
Forge 14.23.2.2624
Dropt 1.7.0
Athaenaeum 1.13.0

Thank you!
Luke616

**Comment by codetaylor** [comment]
It has to do with the meta value of decaying leaves changing. For example, an oak leaf block has a meta value of `0`, but when it starts to decay, the meta value of the block changes to `8`.

This behavior is the same as issue #16. Please see that issue for more information.

**Comment by Luke616** [comment]
Thanks for the information - followed the steps you gave and everything is working great now. Cheers
