### ISSUE TITLE
Use empty hand

### ISSUE THREAD

**Issue by ghost** [codetaylor/dropt#24]
Perhaps this is already possible but I am too dense to figure it out. Is there any way to force a condition to match an empty hand (in IRuleMatchHarvesterHeldItemMainHand)?

**Comment by codetaylor** [comment]
There is now! :D

Feature available in 1.12.2-1.9.0

See: https://github.com/codetaylor/dropt/blob/master/SYNTAX.md#irulematchharvesterhelditemmainhand

**Comment by ghost** [comment]
Ty! That was quick :)
