### ISSUE TITLE
NBT on blocks

### ISSUE THREAD

**Issue by Shane371** [codetaylor/dropt#30]
having a problem getting NBT data to work for match:blocks. I'm using /dropt hand to get the string.
snippet of the code 
https://pastebin.com/7iVVj4x9

I get the error [PARSE] too many segments in
["horsepower:chopping_block:0#{textureBlock:{id:\"minecraft:log\",Count:1b,Damage:1s}}"]

**Comment by codetaylor** [comment]
Right, blocks don't have NBT, only items have NBT.

**Comment by codetaylor** [comment]
Also, Dropt isn't set up to do NBT matching on items, just in case you try it that way too. It does allow setting dropped items with NBT though.

**Comment by codetaylor** [comment]
You can use the `/dropt verbose` command then break the block of interest, and it will display the string of the broken block in chat. You probably want `horsepower:chopping_block` as the block string.

**Comment by Shane371** [comment]
Thanks for the reply. was hoping to add some unusual interactions/easter eggs  for some blocks based on NBT. Some of the blocks dont have an item dropped so I'll just have to use something in harvester to change the affect.
