### ISSUE TITLE
JEI Support

### ISSUE THREAD

**Issue by SihenZhang** [codetaylor/dropt#36]
What about add JEI Support so that players can know how to get things without tips?

**Comment by codetaylor** [comment]
I think JEI support would be amazing!

At first glance, I'm not sure how it would work though. Dropt rules can get pretty complex and it would be difficult to represent that complexity in JEI.

**Comment by UnlimatedStone9** [comment]
If it's an issue of displaying them, there is an addon for JEI called Block Drops, you could develop integration for that?

**Comment by codetaylor** [comment]
Thanks, I'll look into that mod sometime. :)

https://www.curseforge.com/minecraft/mc-mods/block-drops-jei-addon
https://github.com/KidsDontPlay/BlockDrops

**Comment by SihenZhang** [comment]
At first, I just saw a mod named [Re-Fraction](https://www.curseforge.com/minecraft/mc-mods/re-fraction) which is an addon of [Scavenge](https://www.curseforge.com/minecraft/mc-mods/scavenge) is similar to this mod, and that mod has JEI Support. 
I'm a modpack maker using Dropt, so I opened this issue and hoped this mod would be better, because some function of this mod is more powerful. 
I think you can have a look at that mod to see how to make JEI Support.
