### ISSUE TITLE
Couldn't reload and other issues

### ISSUE THREAD

**Issue by Rongmario** [codetaylor/dropt#41]
Crash: https://pastebin.com/qPbRi7GN

My configs:
https://pastebin.com/7VemBScL
https://pastebin.com/AZNHCsiT
https://pastebin.com/6Yb5jaVg

I've been getting really weird results with my configuration. Sometimes the drop works, sometimes the drop gets assigned to every single block broken, I'm at a loss right now...

**Comment by codetaylor** [comment]
Yeah, I don't know offhand.

Using the debug feature may shed some light on why a rule is not behaving as expected.

https://github.com/codetaylor/dropt/blob/master/DEBUG.md

**Comment by codetaylor** [comment]
Looks like the crash is because a `null` made it into an items array in one of your scripts.

This can happen with a trailing comma like so:

```
"items": [
  "minecraft:gravel",
]
```

I've put a null check in the item parser to eliminate the crash going forward.

**Comment by Rongmario** [comment]
Thanks. I tried having debug but nothing would print, was very weird.
