### ISSUE TITLE
Crash on gamestart (mod sorting cycle)

### ISSUE THREAD

**Issue by MasterEnderman** [codetaylor/dropt#45]
![image](https://user-images.githubusercontent.com/24524662/49367240-be954080-f6eb-11e8-8866-ba2f78c92dd5.png)

Forge: 14.23.5.2794
Athenaeum: 1.15.0
Dropt: 1.11.1

**Comment by TimGoll** [comment]
Happens with forge *.68 too and does not depend on other mods

**Comment by codetaylor** [comment]
Thank you for bringing this to my attention.

Should be fixed in 1.12.2-1.11.2
