### ISSUE TITLE
Add IRuleMatchHarvester type for "real player" and "fake player"

### ISSUE THREAD

**Issue by Luke616** [codetaylor/dropt#50]
Hello,

Would like to suggest a feature which I don't believe is currently in dropt. Right now the only player types supported are "any", "player", and "non_player". The issue is that many mods include automation which acts like a player, and thus still triggers under the "player" condition. Having a separate condition for "real_player" and "fake_player" to catch automation behaving as a player would make dropt a more powerful tool for pack developers.

It may help you to see how other mods accomplish this. I know that InControl and FxControl by McJty have "real player" and "fake player" conditions for their actions, here is a link to that mod's homepage and their source code.

https://minecraft.curseforge.com/projects/in-control
https://github.com/McJtyMods/InControl

Thanks for your consideration!
- Luke

**Comment by codetaylor** [comment]
Available in 1.12.2-1.14.0

**Comment by Luke616** [comment]
Wow, that was quick! Thank you so much
