### ISSUE TITLE
/dropt verbose not displaying blockids

### ISSUE THREAD

**Issue by WittyWhiscash** [codetaylor/dropt#60]
#### Intro

Please follow the template when submitting an issue.

If you do not follow the template , your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

You may delete this intro section.

#### Issue Description

*[replace]*

The command /dropt verbose does not provide any info.

*[/replace]*

#### What Happens

*[replace]*

- Create a new survival world with the affected Minecraft and mod versions. Ensure cheats are allowed.
- Run the command `/dropt verbose`
- Mine a wood log block.

*[/replace]*

#### What You Expect to Happen

*[replace]*

I would assume that the `/dropt verbose` command would confirm itself and then start logging blocks broken to the chat. In this case, it should log the wood being broken.

*[/replace]*

#### Script

*[replace]*

https://hastebin.com/lizecepifi.cpp

*[/replace]*

#### Crash Log

*[replace]*

Latest Log (Attached because it is too big):
[latest.log](https://github.com/codetaylor/dropt/files/3526695/latest.log)

*[/replace]*

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 1.12-4.1.19
* Dropt: 1.12.2-1.3.3
* Athenaeum: 1.12.2-1.17.3

**Comment by codetaylor** [comment]
Can you also please link your `crafttweaker.log` that was complaining about not being able to find Dropt?

**Comment by WittyWhiscash** [comment]
[crafttweaker.log](https://github.com/codetaylor/dropt/files/3526736/crafttweaker.log)
