### ISSUE TITLE
Harvester blacklist on held item both matches and does not match.

### ISSUE THREAD

**Issue by therealpygon** [codetaylor/dropt#61]
I think there are a couple logic issues in the HeldItemMatcher checkAsBlacklist() code.

I believe the issues are:

https://github.com/codetaylor/dropt/blob/6c24c93b343d48ea0e84d7b613967170d3c635d3/src/main/java/com/codetaylor/mc/dropt/modules/dropt/rule/match/HeldItemMatcher.java#L243

Should continue if not matched (L251), rather than matched(L243).

https://github.com/codetaylor/dropt/blob/6c24c93b343d48ea0e84d7b613967170d3c635d3/src/main/java/com/codetaylor/mc/dropt/modules/dropt/rule/match/HeldItemMatcher.java#L287

Should return false if not tags because item matched blacklist.

**Comment by codetaylor** [comment]
Additional info from Discord:

![image](https://user-images.githubusercontent.com/1240716/64280367-cf3a4780-cf05-11e9-84b3-4fecb355defc.png)

**Comment by codetaylor** [comment]
Thanks for the report!

Yeah, there was some junk logic in there. Looks like it was introduced in 1.16.0 with the NBT matching stuff. I'm fairly certain I've fixed it in 1.16.1
