### ISSUE TITLE
Can't remove drops by breaking furnaces, beds, chests, ect.

### ISSUE THREAD

**Issue by Eruannie** [codetaylor/dropt#64]
#### Issue Description

When i try to replace/remove drops from furnaces and beds, they won't work like normal blocks and they drop them self.

#### What Happens

If i change/remove a drop from a normal block or a crafting table, it changes his drop, but it don't when I use furnaces or beds.

#### What You Expect to Happen

I expect furnaces and beds to not dropping anything when they're broke.

#### Script

https://pastebin.com/6Rua4yXH

#### Affected Versions

* Minecraft: 1.12.2
* Forge: forge-14.23.5.2824
* CraftTweaker: none
* Dropt: dropt-1.12.2-1.16.1
* Athenaeum: athenaeum-1.12.2-1.17.4

**Comment by codetaylor** [comment]
Check out https://dropt.readthedocs.io/en/latest/blockstrings/

It's probably why your rule isn't matching properly.

You're welcome to join the discord for script assistance: http://discord.codetaylor.com :)
