### ISSUE TITLE
Mod support for explosion harvesting

### ISSUE THREAD

**Issue by CelestialPhoenix** [codetaylor/dropt#68]
Issue Description

Some explosives from mods don't work with the explosion harvester (I think they use a different explosion handler??) (Such as Immersive Engineering and IndustrialCraft).
(the block drops its standard drop instead of the explosive drop specified in the script)
Would it be possible to add support for those mods please?

Script
The script itself works perfectly fine with Vanilla TNT, and a some modded explosives.
https://github.com/CelestialPhoenix/BS-G-1.12-Pack/blob/master/scripts/Block%20Drops/Taint.zs#L50

Affected Versions
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.20
* Dropt: 1.17.0
* Athenaeum: 1.17.4
* IndustrialCraft: 2-2.8.170-ex112 (Industrial TNT, Dynamite(s))
* Immersive Engineering: 0.12.-92 (Gunpowder Barrel)

**Comment by codetaylor** [comment]
For these mods to work with Dropt, they must fire these events in the following order:
1. `ExplosionEvent.Detonate`
2. `BlockEvent.BreakEvent`

IE does not do this:
https://github.com/BluSunrize/ImmersiveEngineering/blob/f2334410de60bc8e8d65ad2921f58e9fe37e784c/src/main/java/blusunrize/immersiveengineering/common/blocks/wooden/BlockWoodenDevice0.java#L84

I didn't look at IC2, but I assume it's not firing the events.
