### ISSUE TITLE
Beds

### ISSUE THREAD

**Issue by AechtRob** [codetaylor/dropt#70]
First - this is a mod I have been waiting an age for, and it's good!

dropt-1.12.2-1.17.0: It seems that beds are not recognised by the mod? I would like to replace a bed dropping itself with a bed dropping some constituent parts instead, but I can't get it to interact with beds at all. Sample script that doesn't work trying to exchange brown bed drops for brown wool etc:
```

  {	  
      "match": {
        "drops": {
          "drops": [
            "minecraft:bed:12"
          ]
        }
      },
      "replaceStrategy": "REPLACE_ITEMS",
      "drops": [
        {
          "item": {
            "items": [
              "minecraft:wool:12
            ]
          }
        }
      ]
    }
```

**Comment by codetaylor** [comment]
Thank you for the compliment! :)

Unfortunately, Dropt can't replace beds. When a bed is broken, its drop is spawned directly in the world and bypasses the event that Dropt uses to do matching and replacements.

**Comment by codetaylor** [comment]
@AechtRob I'm going to reopen this because I'm working on a solution that will allow Dropt to intercept the bed's drops.

**Comment by AechtRob** [comment]
Great - at the moment I am using two added different mods just to bridge the bed-drop issue (as well as using yours for other items).

**Comment by codetaylor** [comment]
I've implemented the solution as a tiny, stand-alone mod that replaces the vanilla bed with a version that fires and respects the harvest drops event.

You can find it here: https://www.curseforge.com/minecraft/mc-mods/dropt-bed

This will make the bed compatible with Dropt as well as any other mod that uses the harvest event.
