### ISSUE TITLE
Minecraft crashes at world creation

### ISSUE THREAD

**Issue by ghost** [codetaylor/dropt#73]
#### Issue Description

Minecraft crashes at world loading (existing world or new one).
I post all this here cuz the second line of my crash-report is:
` at com.codetaylor.mc.dropt.modules.dropt.rule.RuleLocator.cacheRules(RuleLocator.java:74)`

#### What Happens

I joined my old world. And before the world even started render, I've seen "shutting down internal server" screen, and that's all. I tried to create a new world. But the result was the same. 

#### What You Expect to Happen

I tested my dropt rules a little bit earlier. Everything worked fine. But then I exported all pyrotech rules to add a few blocks to existing dropt rules from other mods. And also I turned off pyrotech dropt module, as I had all the rules I needed in my dropt folder.
I deleted all my rules form dropt folder and enabled Pyrotech Dropt module. But nothing changed. 

#### Crash Log

Here is my crash-report from BOP world: https://pastebin.com/rvHnhRL9
And here is my crash-report from default world generation: https://pastebin.com/zi0ZJkG2

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker: 4.1.20.574
* Dropt: 1.18.0
* Athenaeum: 1.19.1

**Comment by codetaylor** [comment]
The crash indicates that a `null` entry has found its way into your rule list.

This is usually indicative of a misplaced comma in a json array due to the way that gson deserializes the json.

For example the array `["one", "two",]` will be parsed as `["one", "two", null]` and `["one",,"three"]` will be parsed as `["one", null, "three"]`.

**Comment by ghost** [comment]
Thanks! It helped immediately, and I was so happy so I forgot to close the issue. I'm so sorry about that
