### ISSUE TITLE
Add support for JEI

### ISSUE THREAD

**Issue by vizthex123** [codetaylor/dropt#76]
Not sure which author to report to, so I'll just do both.

But I was wondering if you could add support for the Block Drops add-on for JEI, as changing drops doesn't update the JEI UI.

PS: Could you add a "suggestion" template without all the instruction spam?

**Comment by codetaylor** [comment]
Unlikely. The full gamut of Dropt's complexity is too difficult to express cleanly in a JEI format.

**Comment by codetaylor** [comment]
https://github.com/KidsDontPlay/BlockDrops/issues/62

**Comment by vizthex123** [comment]
Well, I was hoping it could just read the file and show the new items. Ah well.
