### ISSUE TITLE
Plant blocks drop configured item when the block underneath is broken 

### ISSUE THREAD

**Issue by mechobree** [codetaylor/dropt#78]
#### Issue Description

I have a json file for a drop replacement for some plant blocks that require a tool to get. However, when you mine the block underneath you can totally bypass the tool requirement because it drops 100% of the time.

#### What Happens

Plant blocks drop their configured drops when the block underneath them is broken, even though tools are required to get the drop.

#### What You Expect to Happen

The plants to drop nothing, to act like I broke them with my bare hands.

#### Script

[My json script](https://pastebin.com/gLS08xHz)

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Dropt: 1.18.0
* Athenaeum: 1.19.2

**Comment by codetaylor** [comment]
Omitting `type` in the `harvester` block will default to `ANY` which will match any harvester, even null harvesters.

Set `type` to `PLAYER` and the rule will not match if a player holding the thing doesn't break it.

Please use the discord for script help: http://discord.codetaylor.com.
