### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Xaikii** [codetaylor/dropt#9]
Heya :)

I've read the whole wiki/syntax and correct if I am wrong but could it be that it's not possible to use chances? What I understood from it was that you can use Weight, what will put the name into the pool by the weight amount and at the end pick 1(or how many drops you choose). 
And that would mean that the block would have a 100% chance of dropping at least 1 thing, now I wanted to add stick dropped by ore:treeLeaves with a chance of 15% and came across that problem ^^' 
I am a person who prefers using Chance instead of Weight especially for drops ^^'

My second suggestion would be the same as in artisan-worktable :) 
a Skillable Level Condition Support :)

**Comment by codetaylor** [comment]
It is possible to use chances through the weight system. Have a look at [Example #1](https://github.com/codetaylor/dropt/blob/master/EXAMPLE.md#example-1).

The first drop contains dye items and has a weight of 25. The second drop contains *no items* and has a weight of 75. This means that 25% of the time, it will replace all drops with a dye, and 75% of the time, it will do nothing.
